# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test_TabBarCoordinator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test_TabBarCoordinator
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'

  target 'Test_TabBarCoordinatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test_TabBarCoordinatorUITests' do
    # Pods for testing
  end

end
