# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test_Coordinator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test_Coordinator
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'

  target 'Test_CoordinatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test_CoordinatorUITests' do
    # Pods for testing
  end

end
